// Generated by ToffeeScript 1.6.3-1
(function() {
  var childproc;

  childproc = require('child_process');

  exports.process = function(node, tree, cb) {
    var e, err, out,
      _this = this;
    childproc.exec("coffee -o " + node.out + " -c " + node.files, function() {
      e = arguments[0], out = arguments[1], err = arguments[2];
      console.log(out);
      console.log(err);
      return cb(e, out + '\n' + err);
    });
  };

}).call(this);
